-- =============================================
-- INICIALIZACIÓN DE SUPABASE - FOTOCOPIAS RAMOS
-- =============================================

-- 1. TABLA PRODUCTOS
CREATE TABLE public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL, -- 'Escolar', 'Oficina', 'Servicios', 'Arte'
    precio_costo NUMERIC(10, 2) DEFAULT 0, -- Privado
    precio_venta NUMERIC(10, 2) NOT NULL, -- Público
    stock_actual INTEGER DEFAULT 0,
    stock_minimo INTEGER DEFAULT 5,
    sku TEXT UNIQUE,
    imagen_url TEXT,
    es_servicio BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA VENTAS (Cabecera)
CREATE TABLE public.ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    metodo_pago TEXT DEFAULT 'Efectivo', -- 'Efectivo', 'Tarjeta', 'QR'
    usuario_id UUID REFERENCES auth.users(id) -- Quién hizo la venta
);

-- 3. TABLA DETALLE_VENTAS (Items)
CREATE TABLE public.detalle_ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES public.ventas(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES public.productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL, -- Precio al momento de la venta
    subtotal NUMERIC(10, 2) NOT NULL
);

-- 4. BUCKET DE IMÁGENES (Storage)
-- Nota: Esto se debe configurar en la UI de Supabase, pero aquí dejamos la política
-- Crear un bucket público llamado 'productos-img' en la sección Storage.

-- =============================================
-- SEGURIDAD Y PERMISOS (ROW LEVEL SECURITY)
-- =============================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_ventas ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS PARA PRODUCTOS
-- 1. Lectura pública (para el sitio web)
CREATE POLICY "Productos visibles para todos" 
ON public.productos FOR SELECT 
TO anon, authenticated 
USING (true);

-- 2. Escritura solo para admin (autenticados)
CREATE POLICY "Admin puede gestionar productos" 
ON public.productos FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- POLÍTICAS PARA VENTAS
-- Solo los usuarios autenticados (cajeros/admin) pueden ver y crear ventas
CREATE POLICY "Solo personal ve ventas" 
ON public.ventas FOR ALL 
TO authenticated 
USING (true);

CREATE POLICY "Solo personal ve detalles" 
ON public.detalle_ventas FOR ALL 
TO authenticated 
USING (true);

-- =============================================
-- VISTA PÚBLICA (SEGURIDAD EXTRA)
-- =============================================
-- Esta vista oculta el precio de costo y el stock mínimo a la web pública
CREATE OR REPLACE VIEW public.catalogo_web AS
SELECT 
    id, 
    nombre, 
    categoria, 
    precio_venta as precio, 
    stock_actual as stock, 
    imagen_url,
    sku
FROM public.productos
WHERE stock_actual > 0 OR es_servicio = TRUE;

-- =============================================
-- FUNCIONES (LÓGICA DE NEGOCIO)
-- =============================================
create or replace function descontar_stock(p_id bigint, p_cantidad int)
returns void
language plpgsql
as $$
begin
  update public.productos
  set stock_actual = stock_actual - p_cantidad
  where id = p_id;
end;
$$;