-- =============================================
-- INICIALIZACIÓN DE SUPABASE - FOTOCOPIAS RAMOS
-- =============================================

-- 1. TABLA PRODUCTOS
CREATE TABLE public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL, -- 'Escolar', 'Oficina', 'Servicios', 'Arte'
    precio_costo NUMERIC(10, 2) DEFAULT 0, -- Privado
    precio_venta NUMERIC(10, 2) NOT NULL, -- Público
    stock_actual INTEGER DEFAULT 0,
    stock_minimo INTEGER DEFAULT 5,
    sku TEXT UNIQUE,
    imagen_url TEXT,
    es_servicio BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA VENTAS (Cabecera)
CREATE TABLE public.ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    metodo_pago TEXT DEFAULT 'Efectivo', -- 'Efectivo', 'Tarjeta', 'QR'
    usuario_id UUID REFERENCES auth.users(id) -- Quién hizo la venta
);

-- 3. TABLA DETALLE_VENTAS (Items)
CREATE TABLE public.detalle_ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES public.ventas(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES public.productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL, -- Precio al momento de la venta
    subtotal NUMERIC(10, 2) NOT NULL
);

-- 4. BUCKET DE IMÁGENES (Storage)
-- Nota: Esto se debe configurar en la UI de Supabase, pero aquí dejamos la política
-- Crear un bucket público llamado 'productos-img' en la sección Storage.

-- =============================================
-- SEGURIDAD Y PERMISOS (ROW LEVEL SECURITY)
-- =============================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_ventas ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS PARA PRODUCTOS
-- 1. Lectura pública (para el sitio web)
CREATE POLICY "Productos visibles para todos" 
ON public.productos FOR SELECT 
TO anon, authenticated 
USING (true);

-- 2. Escritura solo para admin (autenticados)
CREATE POLICY "Admin puede gestionar productos" 
ON public.productos FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- POLÍTICAS PARA VENTAS
-- Solo los usuarios autenticados (cajeros/admin) pueden ver y crear ventas
CREATE POLICY "Solo personal ve ventas" 
ON public.ventas FOR ALL 
TO authenticated 
USING (true);

CREATE POLICY "Solo personal ve detalles" 
ON public.detalle_ventas FOR ALL 
TO authenticated 
USING (true);

-- =============================================
-- VISTA PÚBLICA (SEGURIDAD EXTRA)
-- =============================================
-- Esta vista oculta el precio de costo y el stock mínimo a la web pública
CREATE OR REPLACE VIEW public.catalogo_web AS
SELECT 
    id, 
    nombre, 
    categoria, 
    precio_venta as precio, 
    stock_actual as stock, 
    imagen_url,
    sku,
    es_servicio
FROM public.productos;

-- =============================================
-- FUNCIONES (LÓGICA DE NEGOCIO)
-- =============================================
create or replace function descontar_stock(p_id bigint, p_cantidad int)
returns void
language plpgsql
as $$
begin
  update public.productos
  set stock_actual = stock_actual - p_cantidad
  where id = p_id;
end;
$$;


-- =============================================
-- POLÍTICAS PARA VENTAS
-- =============================================
-- 1. Agregar columnas para identificar al cliente web
ALTER TABLE public.ventas 
ADD COLUMN IF NOT EXISTS cliente_nombre TEXT,
ADD COLUMN IF NOT EXISTS cliente_telefono TEXT,
ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'completado'; -- 'pendiente' (web) o 'completado' (pos)

-- 2. Permitir que la Web Pública (usuarios anónimos) pueda CREAR pedidos
-- OJO: Solo permitimos INSERT, no ver ni editar ventas de otros.
-- 2. (DESHABILITADO POR SEGURIDAD) - Usamos RPC 'crear_pedido_web'
-- CREATE POLICY "Publico crea pedidos web"
-- ON public.ventas FOR INSERT
-- TO anon
-- WITH CHECK (true);

-- CREATE POLICY "Publico crea detalles web"
-- ON public.detalle_ventas FOR INSERT
-- TO anon
-- WITH CHECK (true);

-- 3. (Opcional) Ajustar la vista de historial para mostrar el nombre del cliente
-- No requiere SQL, lo haremos en el frontend.

-- =============================================
-- POLÍTICAS PARA VENTAS
-- =============================================

-- 1. Borrar políticas anteriores para evitar el error "already exists"
DROP POLICY IF EXISTS "Publico crea pedidos web" ON public.ventas;
DROP POLICY IF EXISTS "Publico crea detalles web" ON public.detalle_ventas;
DROP POLICY IF EXISTS "Admin total ventas" ON public.ventas;
DROP POLICY IF EXISTS "Solo personal ve ventas" ON public.ventas;

-- 2. Crear las políticas limpias
-- Permitir que el público guarde ventas (DESHABILITADO - USAR RPC)
-- CREATE POLICY "Publico crea pedidos web"
-- ON public.ventas FOR INSERT
-- TO anon
-- WITH CHECK (true);

-- Permitir que el público guarde los detalles (items) (DESHABILITADO - USAR RPC)
-- CREATE POLICY "Publico crea detalles web"
-- ON public.detalle_ventas FOR INSERT
-- TO anon
-- WITH CHECK (true);

-- Permitir al admin ver y editar todo
CREATE POLICY "Admin total ventas"
ON public.ventas FOR ALL
TO authenticated
USING (true)

-- =============================================
-- FUNCIONES SEGURAS PARA WEB (RPC)
-- =============================================
CREATE OR REPLACE FUNCTION public.crear_pedido_web(
    p_cliente_nombre TEXT,
    p_cliente_telefono TEXT,
    p_total NUMERIC,
    p_detalles JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER -- Ejecutar con permisos de admin (bypassea RLS para escritura)
SET search_path = public -- Seguridad extra
AS $$
DECLARE
    v_venta_id BIGINT;
    v_item JSONB;
BEGIN
    -- 1. Insertar Venta
    INSERT INTO public.ventas (total, metodo_pago, estado, cliente_nombre, cliente_telefono)
    VALUES (p_total, 'Web', 'pendiente', p_cliente_nombre, p_cliente_telefono)
    RETURNING id INTO v_venta_id;

    -- 2. Insertar Detalles
    -- Iteramos sobre el JSONB que recibimos del frontend
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_detalles)
    LOOP
        INSERT INTO public.detalle_ventas (venta_id, producto_id, cantidad, precio_unitario, subtotal)
        VALUES (
            v_venta_id,
            (v_item->>'id')::BIGINT,
            (v_item->>'cantidad')::INTEGER,
            (v_item->>'precio')::NUMERIC,
            ((v_item->>'cantidad')::INTEGER * (v_item->>'precio')::NUMERIC)
        );
    END LOOP;

    -- 3. Retornar ID de venta para el frontend
    RETURN v_venta_id;
END;
$$;
